### ISSUE TITLE
"Color Palette" feature

### ISSUE THREAD

**Issue by bryanjclark** [Khan/SwiftTweaks#102]
A lot of apps have color palettes in 'em. It'd be great to be able to use those colors as jumping-off points for the color picker!

Here's what it might look like:
![color picker palette](https://user-images.githubusercontent.com/868389/28736160-6f6abea4-739d-11e7-9599-4f975b013b39.png)

The idea:
On creating a `TweakStore`, you can optionally pass in a `TweakColorPalette`, which looks something like this:

```swift
struct TweakColorPaletteOption {
  let color: UIColor
  let description: String?
}

struct TweakColorPalette {
  let options: [TweakColorPaletteOption]
}
```

Then, for any tweakable color in SwiftTweaks, you'd be able to select a value from this palette (and then use those as jumping-off points for tweaking color in the interface!)

**Comment by JoeSzymanski** [comment]
As a point of interest, I just saw this library that could potentially be used to help out with the color selection: https://github.com/dillidon/Alerts-Pickers

**Comment by bryanjclark** [comment]
Thanks @JoeSzymanski  - we already have a color-editing UI built in to SwiftTweaks!

**Comment by bryanjclark** [comment]
Closing out because it's not a priority.
