### ISSUE TITLE
Tweaks for Android

### ISSUE THREAD

**Issue by hfossli** [Khan/SwiftTweaks#103]
Hey! Thank you so much for sharing this wonderful library! I love the API and the UI is great! 

Do you happen to know if there is some similar libraries for Android? Are you guys using anything similar on Android in Khan Academy?

**Comment by hfossli** [comment]
Related issue https://github.com/facebook/Tweaks/issues/82

**Comment by hfossli** [comment]
We are starting working on Tweaks for Android now :)

**Comment by bryanjclark** [comment]
Hey! Glad you've been enjoying it :D We don't have something like this for our Android app; compilation times aren't as bad for Android so we never wound up building a general-purpose tool for our Android app. Good luck with the project! :D

**Comment by hfossli** [comment]
Hey! Thanks for getting to me! :) You're right it is not a big problem. Our use case is first and foremost feature flags (booleans) which we use in order to have short lived feature branches and experimental features / fixes. I'll let you know when we publish :)
