### ISSUE TITLE
Creating a new version with Swift 4.0 support.

### ISSUE THREAD

**Issue by SebastianBoldt** [Khan/SwiftTweaks#111]
I am currently referencing the master branch in my podfile to get swift 4.0 support. It would be great if you guys could create a new version, update the podspec accordingly and push the new version to the trunk. 

Thanks in advance.

**Comment by rayray** [comment]
Friendly 5 month reminder, would love to have a release to reference.

**Comment by bryanjclark** [comment]
fa629dad3efbd8e81e89e6e6aa39a572c64db725
