### ISSUE TITLE
Layout bug in TweaksRootViewController

### ISSUE THREAD

**Issue by bryanjclark** [Khan/SwiftTweaks#12]
The tableviews in TweaksRootViewController often don't get the topLayoutGuide update (so their content scrolls under the navigation bar)

Doesn't reproduce now that we don't have the segmented controller in the nav bar (because you can't switch the tab, there's not a path to reproduce the error) but the underlying bug in the layout logic is still there!

**Comment by zubair** [comment]
Hey @bryanjclark Is this still a concern?

**Comment by bryanjclark** [comment]
Hey! No, I’d say this isn’t a concern. I’m going to pull out the `TweaksBackupsListViewController` since #6 is closed, and that’ll address this issue!
