### ISSUE TITLE
View controller retain cycle

### ISSUE THREAD

**Issue by ryanmeisters** [Khan/SwiftTweaks#124]
Thanks for the lib

There is a retain cycle in TweaksViewController. 

`TweaksViewController <--> TweaksRootViewController.delegate`

**Comment by bryanjclark** [comment]
Hi! The `delegate` is marked as `unowned`, so there shouldn't be a retain cycle. Is there something I'm missing here? Feel free to re-open if so! Thanks!

**Comment by ryanmeisters** [comment]
hmm which unowned? I was referring to [this delegate property](https://github.com/Khan/SwiftTweaks/blob/master/SwiftTweaks/TweaksRootViewController.swift#L22)

I think the cycle is actually something like this
TweaksViewController->UINavigationController->TweaksRootViewController->TweaksViewController
