### ISSUE TITLE
Pod install shows conflict in ExampleTweaks

### ISSUE THREAD

**Issue by akivab** [Khan/SwiftTweaks#132]
Just installed pod 4.0.3 , seeing an issue with 
```
    public static let title = Tweak("Text", "Text", "Title", options: ["SwiftTweaks", "Welcome!", "Example"])
```

Seems to require instead the static function call

```
public static let title = Tweak<String>.stringList("Text", "Text", "Title", options: ["SwiftTweaks", "Welcome!", "Example"])
```

Wondering if this is a known issue or not? Straight from installation this causes a compilation error, so didn't know what the preferred resolution would be.

**Comment by ShivaHuang** [comment]
Because  this modification is not included in current release yet.
To use the  new feature, specify in your `Podfile`

```ruby
pod 'SwiftTweaks', :git => 'https://github.com/Khan/SwiftTweaks.git'
```

and run `pod install`.
The installed pod will shown as version `4.0.2`, which is older than the one in cocoapods repo,  but don't worry, it the latest codebase.
