### ISSUE TITLE
Broken layout of floating window

### ISSUE THREAD

**Issue by abekert** [Khan/SwiftTweaks#141]
Layout of floating window should respect the safe area of modern iPhones with notch. Currently, the floating window couldn't be closed at all. Look at the video:

![ezgif-4-cc7fa77e88ee](https://user-images.githubusercontent.com/1617020/99731339-d3cd2a80-2ace-11eb-8487-553a7ecb4045.gif)

**Comment by bryanjclark** [comment]
This is now fixed!
