### ISSUE TITLE
[BUG] Tweak values not preserved between app restarts

### ISSUE THREAD

**Issue by vburojevic** [Khan/SwiftTweaks#153]
- [x] I have read through CONTRIBUTING.md

**Describe the bug**
Latest version (4.1.1) doesn't preserve tweak values between app restarts.
Before that it did preserve the selected values.

**To Reproduce**
1. Change tweak value, i.e. bool one to true
2. Restart the app
3. Tweak value is false

**Expected behavior**
Bool state should be preserved, it should be true when the app restarts.

**Desktop (please complete the following information):**
 - OS: iOS
 - Device: iPhone 12 Pro
 - OS Version: iOS 14

**Comment by bryanjclark** [comment]
Thank you for the report! I'll take a look here, that data should definitely persist between restarts.

**Comment by bryanjclark** [comment]
@vburojevic if you update to v4.1.2, it has the fix -  thank you!

**Comment by vburojevic** [comment]
@bryanjclark thank you for a quick fix, and for your overall effort on this library!
