### ISSUE TITLE
Change ownership?

### ISSUE THREAD

**Issue by csilvers** [Khan/SwiftTweaks#166]
@bryanjclark we are no longer using this project at Khan academy, but it seems like it might be more generally useful.  Would you be interested in us changing the ownership to you?

**Comment by bryanjclark** [comment]
Hi! Yeah, let's do it! Thanks for asking, hope things are going well with y'all! (I guess this means the transition to React Native is fully complete!!!)

**Comment by csilvers** [comment]
It's done!

**Comment by bryanjclark** [comment]
Thanks Craig! 👋
