### ISSUE TITLE
Is SwiftTweaks still maintained / can we add a maintainer?

### ISSUE THREAD

**Issue by danielamitay** [Khan/SwiftTweaks#168]
@bryanjclark is this project still maintained? Are we able to add a new maintainer to help review and shepherd high quality PRs?

This project remains the best possible package for tweaking values in apps without compiling.

There are many improvements that have been made by other devs (some visible in the network graph/forks), but everyone is pointing to their own forks and duplicating work, because this project seems unmaintained. Some examples:
- SwiftUI support
- SearchBar in the tweakVC
- Updates to use latest APIs/replace deprecated APIs
- Privacy manifest

Is there room/appetite for allowing a new maintainer to help shepherd in changes that are broadly useful and safe?

cc @mpetes

**Comment by bryanjclark** [comment]
Hi & thanks for asking! I appreciate the interest - yeah I have largely moved on from iOS dev to web dev since 2021ish, but I would love to keep SwiftTweaks going! I'll get back to you on this. Thanks!

**Comment by bryanjclark** [comment]
Hi, I replied via email (and here) a few weeks ago, but didn't hear back, so I'm going to close this issue.

**Comment by danielamitay** [comment]
Hi yes! Apologies for the delay on my end, and thank you for being open to this!

I will target one of the first changes, the SwiftUI version of TweakWindow, for sometime this week. 

Thank you again!
