### ISSUE TITLE
Design & Build tvOS UI

### ISSUE THREAD

**Issue by bryanjclark** [Khan/SwiftTweaks#20]

**Comment by bryanjclark** [comment]
Please note: if somebody submits a PR for this, I'm very likely to reject it if we haven't reviewed the design first! 

(Sorry, I'm just very picky about UI design and we'd want it to be up to the standards we have for the iPhone SwiftTweaks design!)

❤️

**Comment by bryanjclark** [comment]
Turns out, maybe tvOS isn't popular enough that people need this? I'm gonna close it out because I don't think this is likely to be a thing we wind up building & supporting. (If Khan Academy ever builds a tvOS app, though, I'm sure we'll reopen this!)

**Comment by setoelkahfi** [comment]
Hey @bryanjclark, would you mind reopening this? We have a tvOS app and need to use this tool.

**Comment by bryanjclark** [comment]
Hi! You’re welcome to fork the repo and build whatever interface you need! But I am not available to design/build/review/merge a tvOS UI into here.

**Comment by setoelkahfi** [comment]
@bryanjclark Ok. Thanks for the reply.
