### ISSUE TITLE
Fix FloatingTweakGroup rotation bugs

### ISSUE THREAD

**Issue by bryanjclark** [Khan/SwiftTweaks#27]
e.g.
- minimize UI, rotate, it'll probably be broken.
- minimize UI, rotate, expand - it'll probably be broken

via https://github.com/Khan/SwiftTweaks/pull/26#discussion-diff-58924046

**Comment by DanielAsher** [comment]
👍

**Comment by bryanjclark** [comment]
I'm just going to close this one since it's been five years and we haven't fixed it yet! Can always reopen it later.
