### ISSUE TITLE
TweakViewController misaligned layout when Personal Hotspot Blue Bar showing

### ISSUE THREAD

**Issue by DanielAsher** [Khan/SwiftTweaks#43]
Hi,

Firstly thanks so much for this project! As a user of FBTweaks I've been waiting for a swift replacement, and I look forward to contributing if possible :)

I have noticed that the Personal Hotspot Blue Bar pushes the TweakViewController beyond the bottom of the window bounds. Screenshot attached:
![img_4319](https://cloud.githubusercontent.com/assets/7915553/15181871/6a8942d0-1781-11e6-9bec-86eaecb3b3ae.png)

Cheers,

Daniel

**Comment by NachoSoto** [comment]
Thanks for the report! :star: that's certainly a bug.

**Comment by bryanjclark** [comment]
Thanks @DanielAsher!

**Comment by DanielAsher** [comment]
I have resolved this by moving the TweakWindow constructor to inside the `func application(application: UIApplication, didFinishLaunchingWithOptions`.

Previously I had:
```
    class AppDelegate: UIResponder, UIApplicationDelegate {

    var coordinator : AppCoordinator!
    var window: UIWindow? = TweakWindow(frame: UIScreen.mainScreen().bounds, tweakStore: StoryTweaks.defaultStore)
...

```
which seems to cause this issue.
