### ISSUE TITLE
Consider making TweakWindow.tweaksViewController `public` accessible

### ISSUE THREAD

**Issue by DanielAsher** [Khan/SwiftTweaks#44]
I would like to present the `TweaksViewController` from a button press, which works well, however, the `FloatingTweakGroupViewController` does not then display (as  `TweaksViewController.floatingTweaksWindowPresenter == nil` in this case)

Making `TweakWindow.tweaksViewController` `public` allows for all the benefits of using `TweakWindow` triggered from any application event.

You can see a simple example on this fork: https://github.com/DanielAsher/SwiftTweaks/commits/fix/floating-window-on-tweak-manual-present

cheers,

Daniel

**Comment by DanielAsher** [comment]
Should I close this? - as this request seems stale. I will continue to work from my own fork. Thanks.

**Comment by bryanjclark** [comment]
Hey, sorry - never got around to answering this question!

The TweakWindow is the owner of its `tweaksViewController`, and as such, it should be the only thing that gets to say what the `tweaksViewController` is doing. 

That said, maybe there's another way to fix this problem. Much like `TweaksViewController` is public, we could probably do some investigation and make `FloatingTweakGroupViewController` public as well, so developers can use that component (without mucking around in TweakWindow's child objects).

Would that solve your use case?

**Comment by DanielAsher** [comment]
That would be amazing. I'm on a stale fork and would love to update to 2.3 :)

**Comment by bryanjclark** [comment]
Great! I'll close this issue and create a new one for the `FloatingTweakGroupViewController` idea.
