### ISSUE TITLE
Can't build target SwiftTweaks to run the example app

### ISSUE THREAD

**Issue by tomaskraina** [Khan/SwiftTweaks#48]
Both downloaded from github and with `pod try SwiftTweaks`.

Probably caused by missing `xcconfig` files?

<img width="1072" alt="screen shot 2016-05-15 at 19 20 11" src="https://cloud.githubusercontent.com/assets/198316/15275684/5cdaa0bc-1ad2-11e6-871d-b8b29fb4eca8.png">

**Comment by albinekcom** [comment]
The problem is that this project contains a submodule. If you want to clone the code with cloning submodule you need to add flag `--recursive` to `git` command. Try this:
`git clone --recursive https://github.com/Khan/SwiftTweaks.git`

**Comment by bryanjclark** [comment]
Thanks for the bug report! I'll take a look!
