### ISSUE TITLE
Allow FloatingTweakGroupViewController to be vertically dragged

### ISSUE THREAD

**Issue by DanielAsher** [Khan/SwiftTweaks#52]
I love the `FloatingTweakGroupViewController` - but sometimes the very part of the current view I'm trying to tweak is obscured by the floating window. Enabling a drag gesture on the floating window would allow us to reposition it and expose the hidden parts of the underlying view.

**Comment by bryanjclark** [comment]
Have you seen the horizontal drag gesture? It gets the floating window tucked to the right-hand side.

**Comment by bryanjclark** [comment]
Hey Daniel! I'm going to close this out - but please feel free to re-open if my suggestion isn't working for you and you still need this feature. Cheers!

**Comment by DanielAsher** [comment]
Hi Bryan,
Thanks again for such a great project. It's wonderful to finally have a state of the art tweaks system for swift.

The use case I have isn't quite dealt with by the 'fold-away' functionality, but it's a good tip.
In particular I thinking of a tweak that works best when the user can directly see the effect while changing the parameter.
This is currently impossible for any effect in the bottom half of the screen.
I'll reopen this, as per your suggestion, when I get to my laptop.
Thanks again,
Daniel
