### ISSUE TITLE
View Controller

### ISSUE THREAD

**Issue by jcampbell05** [Khan/SwiftTweaks#56]
I would love to be able to push on a custom view controller for Swift Tweaks.

**Comment by bryanjclark** [comment]
@jcampbell05 What's the use case for this? If you have more information around what's in the view controller / what use case it would provide for others, I'm all ears! 

For example: is there a different type of thing you're looking to Tweak? A different editing feature for an existing tweak type? Or are you truly wanting to add any arbitrary view controller to the SwiftTweaks interface?

Closing for now, please feel free to re-open if you're willing to elaborate on the above questions!

Cheers.
