### ISSUE TITLE
Changing a tweak with a value > 100 causes the tweak to return to 100

### ISSUE THREAD

**Issue by anuragt84** [Khan/SwiftTweaks#60]
If the initial Int tweak value is set to say 150, and you hit the plus button, the value changes to 101. If you hit the minus button, it changes to 99.  Setting a defaultValue while creating the tweak doesn't fix it either.

**Comment by bryanjclark** [comment]
Thanks for the report, @anuragt84!

Do you have some sample code that reproduces the issue? I'm curious to check out a couple of things:

1. [This Tweak init method](https://github.com/Khan/SwiftTweaks/blob/master/SwiftTweaks/Tweak.swift#L60) should prevent you from creating a `Tweak` where the `defaultValue` is larger than the `maxValue`.
2. There's some code in `TweakViewData` [here](https://github.com/Khan/SwiftTweaks/blob/420424798f9894546bad4a7dc8a9837d1ca52f9b/SwiftTweaks/TweakViewData.swift#L93) that sounds a potential cause of the issue - if you send up some sample code that reproduces the issue I'm happy to check it out!

Cheers, and thanks again for the report!

**Comment by bryanjclark** [comment]
Welp, I'm 100% able to repro. Gonna add a fix here...

**Comment by bryanjclark** [comment]
Ah, just realized what it is - we're setting the `value` on UIStepper before we set the minimum/maximum levels. Fix incoming!

**Comment by anuragt84** [comment]
Thank you so much. Sorry I couldn't be of much help.

**Comment by bryanjclark** [comment]
No worries at all! I really appreciate the bug report!
