### ISSUE TITLE
Write value for tweak programmatically for unit tests

### ISSUE THREAD

**Issue by geoffmacd** [Khan/SwiftTweaks#66]
I need the ability to test behavior when a tweak is enabled/disabled. We are using Tweaks for feature flagging, false turns off in-development features for production. 

Because I am scared new development features may affect production in an unexpected way, I would like to be able to unit test various modules which use tweak. Is there not a way to write a different value programmatically?

**Comment by bryanjclark** [comment]
Closing; feel free to reopen if you've got an update or question!
