### ISSUE TITLE
Swift 3 migration

### ISSUE THREAD

**Issue by DanielAsher** [Khan/SwiftTweaks#68]
Hi,

are there any plans to support swift-3? I see a stale PR #63 and it looks like @richy486 fork is deleted. Should I submit a PR?

thanks,

Daniel

**Comment by ecaselles** [comment]
@NachoSoto @richy486 Hey! We would love to help giving PR #63 the push required to merge it. Not clear what it is missing though. What could we do to get it ready? 💪

**Comment by richy486** [comment]
Not sure what's needed at this stage, waiting for instructions!

**Comment by bryanjclark** [comment]
Hey all! Poking around now.

**Comment by bryanjclark** [comment]
Alright, it's landed on `master`! Closing this issue.

Haven't issued a new release yet, but give it a shot!

**Comment by SebastianBoldt** [comment]
When will there be a new version @bryanjclark ?

**Comment by bryanjclark** [comment]
@SebastianBoldt The stuff at the top of `master` works with Swift 3, feel free to use that! I don't have an official date for the next release - but I'd bet in the next couple of months we'll put a bow on it!
