### ISSUE TITLE
Umbrella Header "SwiftTweaks.h" not found

### ISSUE THREAD

**Issue by TusharGarg** [Khan/SwiftTweaks#77]
I am trying to run the example iOS project attached in the repo. While running it, I am getting the following build error: 

> Umbrella Header "SwiftTweaks.h" not found

_Xcode Version: 8.1_ 

I tried to fix it using information from this [link](http://stackoverflow.com/questions/30355133/swift-framework-umbrella-header-h-not-found) but that didn't help.

**Comment by bryanjclark** [comment]
Thanks for filing the bug! This is a duplicate of #61; closing as a duplicate.

**Comment by TusharGarg** [comment]
Thank you for a quick response @bryanjclark. 
My bad. I should have gone through the list of open issues first.
