### ISSUE TITLE
Compilation with newest Swift, Xcode

### ISSUE THREAD

**Issue by peseriusz** [Khan/SwiftTweaks#95]
When I'm trying to compile sample app, then I get a lot of Swift Compiler Error, it's looks like older Swift version issues. I'm using Xcode 8.3.3

ed: I'm using cocapods version, master branch.

**Comment by peseriusz** [comment]
I found solution. In pod file just use: 

`  pod 'SwiftTweaks', :git => 'https://github.com/Khan/SwiftTweaks.git', :tag => 'v2.0-beta.1'
`

**Comment by bryanjclark** [comment]
Glad you sorted it out! :D
