### ISSUE TITLE
Add all released versions to Cocoapods master repo

### ISSUE THREAD

**Issue by jacobjennings** [Khan/SwiftTweaks#98]
Ideally Cocoapods users should be able to choose from 1.0, 1.1 and 2.0.

**Comment by bryanjclark** [comment]
I'm not sure how to do this, and keeping the pod spec up-to-date for this repo has been more involved than I'd like! I'm going to close this out as `wontfix`, but if people feel strongly I'm happy to reopen! (Cocoapods users can always point their repo to a specific commit if they have a particular version of SwiftTweaks that they want to use, so this doesn't feel like a must-do!)
