### ISSUE TITLE
Simplify cocoapods installation - Dependencies per build configuration

### ISSUE THREAD

**Issue by jacobjennings** [Khan/SwiftTweaks#99]
Cocoapods 0.34 release included an option to enable a Pod for a specific build configuration, something like:

`pod 'SwiftTweaks', :configurations => ['Debug']`

**Comment by bryanjclark** [comment]
What would this change look like to this repo? Can you file a PR? Closing for now - unless I’m missing something here, this is a request that others would specify in their `Podfile`, not something that we’d change in our `.podspec`, right?
